export default {
  BALANCE_LOGIN_RESPONSE: 'USER_BALANCE_LOGIN_RESPONSE',
  BALANCE_LOGOUT: 'BALANCE_LOGOUT',
  AUTH_RESPONSE: 'USER_AUTH_RESPONSE',

  // Main
  GET_USER_INFO_RESPONSE: 'MAIN_GET_USER_INFO_RESPONSE',
  REGISTER_PRODUCT: 'MAIN_REGISTER_PRODUCT',
  SAVE_PHOTO: 'MAIN_SAVE_PHOTO',
  // CATEGORY_SELECT: 'MAIN_CATEGORY_SELECT',
  PRODUCT_TYPE: 'MAIN_PRODUCT_TYPE',
  PRODUCT_CATEGORY1: 'MAIN_PRODUCT_CATEGORY1',
  PRODUCT_CATEGORY2: 'MAIN_PRODUCT_CATEGORY2',
  PRODUCT_CATEGORY3: 'MAIN_PRODUCT_CATEGORY3',
  PRODUCT_CATEGORY4: 'MAIN_PRODUCT_CATEGORY4',
  PRODUCT_CATEGORY5: 'MAIN_PRODUCT_CATEGORY5',
  REQUEST_PRODUCT_LIST: 'MAIN_REQUEST_PRODUCT_LIST',

  // User
  HOWMUCH_PHONENUMBER_RESPONSE: 'USER_HOWMUCH_PHONENUMBER_RESPONSE',
  HOWMUCH_LOGIN_RESPONSE: 'USER_HOWMUCH_LOGIN_RESPONSE',
};
