export default {
  BALANCE_LOGIN_RESPONSE: 'USER_BALANCE_LOGIN_RESPONSE',
  BALANCE_LOGOUT: 'BALANCE_LOGOUT',

  // main
  GET_USER_INFO_RESPONSE: 'MAIN_GET_USER_INFO_RESPONSE',
  REGISTER_PRODUCT: 'MAIN_REGISTER_PRODUCT',
};
