export default {
  BALANCE_LOGIN_RESPONSE: 'USER_BALANCE_LOGIN_RESPONSE',
  BALANCE_LOGOUT: 'BALANCE_LOGOUT',

  // Main
  GET_USER_INFO_RESPONSE: 'MAIN_GET_USER_INFO_RESPONSE',
  REGISTER_PRODUCT: 'MAIN_REGISTER_PRODUCT',
  SAVE_PHOTO: 'MAIN_SAVE_PHOTO',

  // User
  HOWMUCH_PHONENUMBER_RESPONSE: 'USER_HOWMUCH_PHONENUMBER_RESPONSE',
  HOWMUCH_LOGIN_RESPONSE: 'USER_HOWMUCH_LOGIN_RESPONSE',
};
